#!/bin/bash

set -eo pipefail

#
# This script runs static tests which
# can be performed without code execution.
#
# Some example are code sniffing and unit testing
#

# Run composer install to get the vendor directory
composer install --no-ansi --no-interaction --optimize-autoloader --no-progress --no-scripts

# Check coding standards
composer -n code-sniff
